package com.example.farmmate.Entities.GRdv;

public enum TypeCulture {
    CEREALES,         // Blé, orge, maïs, riz...
    LEGUMES,          // Carottes, tomates, pommes de terre...
    FRUITS,           // Pommes, oranges, raisins...
    LEGUMINEUSES,     // Lentilles, pois chiches, haricots...
    PLANTES_OLEAGINEUSES, // Tournesol, colza, olive...
    PLANTES_MEDICINALES, // Menthe, lavande...
    FORESTERIE,       // Arbres pour la production de bois
    FLORICULTURE,     // Culture de fleurs et plantes ornementales

}
